server:
  port: 8080
  servlet:
    context-path: /automatic-irrigation-system/api/v1

spring:
  application:
    name: automatic-irrigation-system

  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:testdb

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: kvnagarjun@gmail.com
    password: ptjyldvevybkvrwv
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true

flyway:
  locations: classpath:/db/migration

automatic-irrigation-system:
  irrigation-check-scheduler: 10000
  mail:
    from: noreply@automatic-irrigation-system.com
    to: nagarjun.kv@gmail.com


feign:
  circuitbreaker:
    enabled: true

resilience4j:
  retry:
    instances:
      retryTriggerSensor:
        max-attempts: 5
        wait-duration: 5s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

  circuitbreaker:
    instances:
      triggerSensorCircuitBreaker:
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 4
        sliding-window-type: count-based
        sliding-window-size: 6
        minimum-number-of-calls: 6
        slow-call-duration-threshold: 15s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60

logging:
  file:
    name: ./log/automatic-irrigation-system.log
